### ISSUE TITLE
Adapting to Python 3

### ISSUE THREAD

**Issue by gustavklopp** [chr15m/PodSixNet#1]
trying to run Server.py:

```
ServerTestCase
--------------
E
======================================================================
ERROR: runTest (__main__.ServerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gus/PodSixNet/Server.py", line 83, in setUp
    self.server = TestServer(channelClass=ServerChannel)
  File "/home/gus/PodSixNet/Server.py", line 22, in __init__
    self.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
AttributeError: 'TestServer' object has no attribute 'setsockopt'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

**Comment by gustavklopp** [comment]
Ok, it's a problem with Python 3. I don't know where is the problem (I've refactored the code thanks to 2to3)...

**Comment by decemer** [comment]
same need

**Comment by selfsame** [comment]
Sorry for the delay, the python3 branch has been updated, along with the examples https://github.com/chr15m/PodSixNet/tree/python3
