### ISSUE TITLE
setup.py can't find PodSixNet/version.py

### ISSUE THREAD

**Issue by nonoesimposible** [chr15m/PodSixNet#24]
How to reproduce: clone the repository and run setup.py

When I tried to run `setup.py` (Python 3.7 if it matters) I got this:

```
$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    exec(open("PodSixNet/version.py").read())
FileNotFoundError: [Errno 2] No such file or directory: 'PodSixNet/version.py'
```

It appears that version.py doesn't exist. I worked around this by just typing in the version to `setup()`:

```
setup(
    version="0.10.0",
    name='PodSixNet',
    description='Multiplayer networking library for games',
    ...
)
```

I don't know what happened to version.py, perhaps it was removed by accident or something.

**Edit:** version.py is inside of `.gitignore`, is this the problem?

**Comment by nonoesimposible** [comment]
Hmm, perhaps it could be as simple as this?  
https://github.com/nonoesimposible/PodSixNet/commit/ecc20489928629cf12e7e833d4c5e330d5f3a58a

**Comment by chr15m** [comment]
@nonoesimpossible thx I will l check yr PR & get this fixed.

**Comment by chr15m** [comment]
@nonoesimposible can you let me know if the fix I just pushed works? You should be able to clone the repository and run setup.py now and it will use the git tag as the canonical version number.

**Comment by nonoesimposible** [comment]
Thank you very much, now setup.py works with Python 2 but fails with Python 3:

```
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    __version__ = subprocess.check_output(["git", "describe", "--tag", "--always"]).strip("\n")
TypeError: a bytes-like object is required, not 'str'
```

I'm not really sure what's going on here, maybe all that needs to be done is convert the output to a string first?

```
    __version__ = str(subprocess.check_output(["git", "describe", "--tag", "--always"])).strip("\n")
```

**Comment by chr15m** [comment]
@nonoesimposible which version of python 3 are you using? I tested in 3 and it seemed to work. Maybe I should just pin the version file as you suggested.

**Comment by nonoesimposible** [comment]
Python 3.7.2

I'm running it with `sudo python setup.py install`.

I'm not sure what the difference would be, in [the check_output documentation](https://docs.python.org/3/library/subprocess.html#subprocess.check_output) it just says this:

```
Changed in version 3.6: encoding and errors were added. See run() for details.

New in version 3.7: text was added as a more readable alias for universal_newlines.
```

**Comment by chr15m** [comment]
@nonoesimposible will fix.

**Comment by chr15m** [comment]
Nope that's all good if it works for you we don't need to do anything else.
