### ISSUE TITLE
[Discussion] lower_case names for methods (PEP 8)?

### ISSUE THREAD

**Issue by McSinyx** [chr15m/PodSixNet#26]
I am aware that this is quite up to personal preference, but many modules I have used followed [that naming convention](https://www.python.org/dev/peps/pep-0008/#prescriptive-naming-conventions), which IMHO makes code more recognizable, i.e. one can easily distinguish between module/class/method/function. [threading](https://docs.python.org/3/library/threading.html) has went smoothly through this kind of migration by aliasing deprecated names to ensure backward compatibility.

Happy lunar new year!

**Comment by chr15m** [comment]
@McSinyx probably a good idea. Will merge a PR that implements this change with the aliasing you suggest.

**Comment by nonoesimposible** [comment]
Would this be a good newcomer bug? I'm interested in helping.

**Comment by chr15m** [comment]
@nonoesimposible indeed! The criteria for success are:

 * Callbacks and methods are available via `lower_case` style names.
 * The tests pass.

**Comment by nonoesimposible** [comment]
So here is something interesting. In Channel.py (will eventually be called channel.py), the send method (previously Send) looks like this:

```python
class Channel(asynchat.async_chat):
    ...
    def send(self, data):
        """Returns the number of bytes sent after encoding."""
        outgoing = dumps(data) + self.endchars.encode()
        self.sendqueue.append(outgoing)
        return len(outgoing)
```

This actually ends up recursively calling send() until my computer runs out of memory. Since the aysnchat.async_chat already has a send() method, I think Channel.send is overriding it and messing things up. Previously, this wasn't happening because Python is case-sensitive, so Send() and send() were two different methods.

Is there a way to get around this without completely renaming Channel.send to something else?

The exception looks like this:

```
Server launched
connection
New Player('127.0.0.1', 44950)
players [<__main__.ClientChannel connected 127.0.0.1:44950 at 0x7fb703bfa668>]
Traceback (most recent call last):
  File "ChatServer.py", line 72, in <module>
    s.launch()
  File "ChatServer.py", line 62, in launch
    self.pump()
  File "/usr/lib/python3.7/site-packages/PodSixNet/Server.py", line 38, in pump
    [c.pump() for c in self.channels]
  File "/usr/lib/python3.7/site-packages/PodSixNet/Server.py", line 38, in <listcomp>
    [c.pump() for c in self.channels]
  File "/usr/lib/python3.7/site-packages/PodSixNet/Channel.py", line 30, in pump
    [asynchat.async_chat.push(self, d) for d in self.sendqueue]
  File "/usr/lib/python3.7/site-packages/PodSixNet/Channel.py", line 30, in <listcomp>
    [asynchat.async_chat.push(self, d) for d in self.sendqueue]
  File "/usr/lib/python3.7/asynchat.py", line 202, in push
    self.initiate_send()
  File "/usr/lib/python3.7/asynchat.py", line 251, in initiate_send
    num_sent = self.send(data)
  File "/usr/lib/python3.7/site-packages/PodSixNet/Channel.py", line 35, in send
    outgoing = dumps(data) + self.endchars.encode()
MemoryError
```

**Comment by chr15m** [comment]
@nonoesimposible thanks for making progress on this. Yes using `.Send()` to avoid overriding `.send()` was not a great hack. I'm not sure what the best solution to fix this is. Some different options:

 * Stop subclassing asynchat and instead compose it in under a new class property.
 * Monkey-patch the class and rename `.send` to something else before overriding it (may cause other errors but tests will probably reveal them).
 * Change the name of the new method to some other verb entirely.

I suppose if the old `.Send()` is still available to code which uses it then whatever we do is ok for existing users so it's more about what's best for future users.

I'll have a think about it, but don't let me stop you from moving ahead.

**Comment by nonoesimposible** [comment]
Hmm, it looks like this is not the only thing that interferes with asyncore's variable names. Some possible instances are:

* `EndPoint.close()` calls itself recursively
* `Channel.handle_connect()` has trouble because `connected` is now a variable instead of a method of EndPoint (perhaps this could be easily taken care of by replacing the name `connected` with something more specific)

Should we handle these (and possibly more undiscovered) cases individually, or should we come up with one solution that tackles them all?

**Comment by chr15m** [comment]
A solution that tackles them all sounds pretty good if you can work one out.

**Comment by pauliyobo** [comment]
You could try by storing the async_chat's instance into a class property instead of inheriting from it. That way send should not conflict with the parent class.

**Comment by pauliyobo** [comment]
sorry if I sound spammy.
Is someone currently working on this issue?

**Comment by nonoesimposible** [comment]
To be honest, I did get stuck a while back with the namespace thing but your recent activity has reminded me of this issue and I'd be happy to give it another try. =)

This is my fault for not communicating well/being honest; if you want to take a shot at fixing this, go ahead.

**Comment by pauliyobo** [comment]
alright. I'll be starting this in a new branch and see what I can come up with.

**Comment by pauliyobo** [comment]
hi there. The API has changed in the following ways
channel.py, connection.py, endpoint.py and server.py are now all lowercase
The methods  of those classes have been modified to be lowercase with underscores while class names have remained the same.
I have some questions.
1. @McSinyx when you say that aliases should be introduced to support backward compatibility, what do you mean?
2. Should I change the callback functions to be lowercase as well, so Network_ will become network_?
Thanks in advance.

**Comment by nonoesimposible** [comment]
> when you say that aliases should be introduced to support backward compatibility, what do you mean?

Suppose someone has used PodSixNet in their game and they wrote the following code:

```python
connection.Send()
```

Now that code won't work any more because `Send()` has been renamed to `send()`. If you make a new method `Send` in that is equal to `send`, people's code won't be instantly broken anymore; that's what backwards compatibility means.

---

> Should I change the callback functions to be lowercase as well, so Network_ will become network_?

Yes, that seems to make sense. Make sure that both `Network_` and `network_` are available.

**Comment by pauliyobo** [comment]
@nonoesimposible hmm, to make it backward compatible I could think either of making a fake class which uses the old naming convention but would actually redirect to the new functions. So whenever we want to get done with it we can just delete the fake class.
As for the examples, I've tested the chatclient and the lagtimeclient, but i can not test the whiteboard client because I'm actually blind therefore I wouldn't be able to see the output.
The only thing I need to convert now is the test.py file.

**Comment by chr15m** [comment]
@pauliyobo great stuff. You can also run the unit tests to see if everything is working like this: `python PodSixNet/test.py`.

When you submit a PR the tests will automatically be run under a few versions of Python, including Python 2 and the result will show up on GitHub.

**Comment by pauliyobo** [comment]
OK, so onething.
Everything seem to work properly, except the fact that test.py gives me one failure. I assume it has been like this because even with the old version I receive the same output.
In addition, on window git fill actually fail to rename filenames across branches. In the branch I'm working on I hace lowercase names while in master I have uppercase filenames. If I switch branches the filenames will remain uppercase Nd I will have to manually rename.
This means that we have to stick to one naming for filenames because git will fail to handle it.

**Comment by pauliyobo** [comment]
Hi there.
Do the latest changes work on your end?

**Comment by chr15m** [comment]
Hello. Sorry, I have not had a chance to look a this yet.

**Comment by NicklasTegner** [comment]
Hi
What is the status of this issue and the associated pull request

**Comment by chr15m** [comment]
@pauliyobo does this have backwards compatibility with people's existing code? What I mean is if somebody is using PodSixNet in their own project and they upgrade, will this upgrade break their code? I think we discussed having aliases to the old function names to avoid the break, did this get implemented?

**Comment by pauliyobo** [comment]
@chr15m as of now, yes.
I've started to implement some aliases.
Currently, I've aliased the modules in __init__.py importing all of the PodSixNet modules and for example doing:

```python
Channel = channel
```

In the classes I'm aliasing methods in the following way:

```python
# let's pretend that this line contains a class definition with a method named pump
# minimal channel example
class Channel():
    def pump(self):
        print("pumping")

    # to alias the method I'd just do
    Pump = pump
```

While this would work when methods are called, when the user has to define the methods in the respective classes everything would mess up because internally the aliases wouldn't be used.

A possible solution I thought could work is to readd the modules with the old naming convention, and make the classes in the modules inherit from the classes of the new naming convention.
Would this be an acceptable solution for you?

**Comment by McSinyx** [comment]
> when the user has to define the methods in the respective classes everything would mess up because internally the aliases wouldn't be used

Could you please elaborate (by an example)?

**Comment by chr15m** [comment]
@McSinyx I think what @pauliyobo means is when the user has to override the [virtual] method with their own supplied method, it won't worry properly because the call will be to the new one.

@pauliyobo wrote:
> A possible solution I thought could work is to readd the modules with the old naming convention, and make the classes in the modules inherit from the classes of the new naming convention.

Yeah, that sounds like it could work.

The other alternative would be to simply do a release with deprecation warnings everywhere and then make this changed version the 2.0 version.

**Comment by NicklasTegner** [comment]
I'm in favor of making it a version 2.0, simply because, there's also other parts of the code that could use some cleanup / rewriting.

**Comment by pauliyobo** [comment]
@McSinyx  Currently the aliases  I've implemented are simply class attributes that reference the current implementation
Which means that in channel.py the alias Pump when called will just call pump.
I know it's a bit confusing. Let's see if I can illustrate this with an example

```python
# I'll do a class that has nothing to do with the project just to explain
class person:
    def hi(self):
        print("hi")

    greet = hi
```

As you can see greet is an alias to hi. It just holds the reference to the method hi which means that calling

```python
Person.greet()
```

is the same as doing

```python
Person.hi()
```

However, if I were to do a subclass of Person, and override what greet does greet wouldn't have nothing to do with hi any more, but I want greet to just be an alias.
In this case, it wouldn't matter, but since in our case the code that is in those methods actually communicate with the whole environment, if I for instance were to override a method that is just an alias, the code would probably be never used from the library it's self.
Not sure if this is clear enough
I also am horrible with method names :)

**Comment by pauliyobo** [comment]
@chr15m Personally I'd just release 2.0.
People can use the older version to maintain their codebase, and they can surely upgrade should they want new features when they are added.
To make things easier we could even write a guide on how to upgrade, even though it's literally just renaming some calls and imports.

**Comment by NicklasTegner** [comment]
In addition, if we were to go with releasing a version 2.0, that would also give us the ability to drop Python 2 support (since python 2 has reached it's EOL) and switch from asynchat/asyncore (which has been deprecated in 3.6) to asyncio.

**Comment by chr15m** [comment]
Ok, what I think we should do is make all of these changes you guys have suggested, including:

 * Merging @pauliyobo's method renaming patch.
 * Using `rencode` external library.
 * Dropping Python 2 support.
 * Porting to asyncio.
 * Updating string handling code.

Then release it under a new name on pypi, such as `PodSixNet2`. This will mean that old codebases don't break, but people who want to get the latest and greatest can `pip install PodSixNet2`. Renaming the project isn't something you want to do often, but with so many backwards incompatible changes I think it's required here.

What are your preferences for the name of the new package?

 * `PodSixNet2`
 * `PodSixNetNG`
 * `PodSevenNet`
 * Other ideas?

**Comment by NicklasTegner** [comment]
I would like the name PodSixNet2, since an import statement would look like this

from podsixnet2 import *

On that note, can we please have the actual imported package be all lowercase.

**Comment by nonoesimposible** [comment]
What was the etymology behind the name "PodSixNet?" Perhaps we could come up with something clever but entirely different in order to make the difference between the two versions obvious.

**Comment by chr15m** [comment]
I had a one person game company called PodSix Games a long time ago:

https://web.archive.org/web/20120629091658/http://podsix.com.au/pod/Games

It was named after this Sealab 2021 episode wherein the phrase "PodSix was jerks!" was uttered by the captain:

https://youtu.be/zo9hqmkEfEY?t=524

**Comment by pauliyobo** [comment]
I'm fine with either PodSixNetNG or PodSixNet2

**Comment by nonoesimposible** [comment]
`podsixnet2` (all lowercase) would be my preference because by retaining the same string of characters, the new version will be easy for existing users to discover and will give them the impression that it is still the same library, just with major improvements.

Another alternative would be `podsixnet1` because programmers count from 0.

**Comment by chr15m** [comment]
> Another alternative would be podsixnet1 because programmers count from 0.

Ha ha ha.

Ok, can anyone get together a PR that updates the package name, tests, etc.? I'll ship it to pypi and then we can merge @pauliyobo's patch. :rocket:

**Comment by nonoesimposible** [comment]
> Ok, can anyone get together a PR that updates the package name, tests, etc.?

So `podsixnet2` is the final package name? And just to clarify, the new version should be on PyPI before we do other plans for the next version such as porting to `asyncio`?

**Comment by NicklasTegner** [comment]
I really think that @pauliyobo  should just update the package name and then @chr15m  can merge that as version 2.0, change the package name and publish to pypi.
alternatively archive this repository and make a podsixnet2 GitHub repository.

**Comment by pauliyobo** [comment]
If this version is going to be deprecated anyway, it would be pointless to implement aliases for it. It probably would be better to focus with the new convention on the version 2.0.
What do you think?

**Comment by NicklasTegner** [comment]
Either way implementing the aliasing would be pointless, now that it gets moved to a new namespace. But it really depends on what @chr15m  want's to do.

**Comment by chr15m** [comment]
Yes I think don't worry about the aliases. The point of changing the name is so we can break backwards compatability with the current API without breaking anybody's project.

I'll think about the best way to do this with regards to documentation etc. today.

**Comment by NicklasTegner** [comment]
@chr15m  did you come up with something, what's the current status?

**Comment by nonoesimposible** [comment]
If I understand correctly, a merge request is ready but it breaks backwards compatibility, so now we have to go through the trouble of making a new major release before the changes are marked as stable.

**Comment by NicklasTegner** [comment]
Either that, or @chr15m  would change the name, and make a new repository and then mark this one as deprecated

**Comment by chr15m** [comment]
@pauliyobo @NicklasTegner @nonoesimposible there is now a `podsixnet2` branch and a release up on pypi: https://pypi.org/project/podsixnet2/

Please issue pull requests against the `podsixnet2` branch. Once you guys let me know I'll merge it into `master`.
